; Script generated by Inno Setup Script Wizard for QLQuanPho Application
; Hướng dẫn: Mở file này trong Inno Setup Compiler và Build (F9)

#define MyAppName "Quản Lý Quán Phở"
#define MyAppVersion "1.0"
#define MyAppPublisher "PhoManager"
#define MyAppExeName "QLQuanPho.exe"

[Setup]
; Thông tin ứng dụng
AppId={{DC19C05E-821E-44A7-8339-66E08B7C3390}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=
OutputDir=Setup
OutputBaseFilename=QLQuanPho_Setup
SetupIconFile=
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon={app}\{#MyAppExeName}

; Các file cần cài đặt
; LƯU Ý: Trước khi build setup, cần build project ở chế độ Release:
; Visual Studio: Build -> Configuration Manager -> Chọn "Release" -> Build -> Rebuild Solution
; Nếu chưa có Release, script sẽ tự động dùng Debug build
[Files]
; File chính của ứng dụng (ưu tiên Release, nếu không có thì dùng Debug)
Source: "bin\Release\QLQuanPho.exe"; DestDir: "{app}"; Flags: ignoreversion; Check: DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Debug\QLQuanPho.exe"; DestDir: "{app}"; Flags: ignoreversion; Check: not DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Release\QLQuanPho.exe.config"; DestDir: "{app}"; Flags: ignoreversion; Check: DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Debug\QLQuanPho.exe.config"; DestDir: "{app}"; Flags: ignoreversion; Check: not DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion; Check: DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Debug\*.dll"; DestDir: "{app}"; Flags: ignoreversion; Check: not DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Release\*.xml"; DestDir: "{app}"; Flags: ignoreversion; Check: DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Debug\*.xml"; DestDir: "{app}"; Flags: ignoreversion; Check: not DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Release\logo.png"; DestDir: "{app}"; Flags: ignoreversion; Check: DirExists(ExpandConstant('{src}\bin\Release'))
Source: "bin\Debug\logo.png"; DestDir: "{app}"; Flags: ignoreversion; Check: not DirExists(ExpandConstant('{src}\bin\Release'))

; SQL Scripts
Source: "PhoManager.Database\*.sql"; DestDir: "{app}\Database"; Flags: ignoreversion

; Tạo thư mục Logs
[Dirs]
Name: "{app}\Logs"; Permissions: users-modify

; Shortcuts
[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

; Tasks (tùy chọn khi cài đặt)
[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1

; Chạy sau khi cài đặt
[Run]
; Chạy ứng dụng sau khi cài đặt (tùy chọn)
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; Code để kiểm tra .NET Framework 4.8
[Code]
function IsDotNet48Installed: Boolean;
var
  Release: Cardinal;
  Success: Boolean;
begin
  Result := False;
  Success := RegQueryDWordValue(
    HKEY_LOCAL_MACHINE,
    'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full',
    'Release',
    Release
  );
  
  if Success then
  begin
    // .NET Framework 4.8 = Release >= 528040
    // .NET Framework 4.7.2 = Release >= 461808
    // .NET Framework 4.7.1 = Release >= 461308
    // .NET Framework 4.7 = Release >= 460798
    Result := Release >= 528040;
  end;
end;

function InitializeSetup(): Boolean;
var
  ErrorCode: Integer;
begin
  Result := True;
  
  // Kiểm tra .NET Framework 4.8
  if not IsDotNet48Installed then
  begin
    if MsgBox(
      'This application requires .NET Framework 4.8.' + #13#10#13#10 +
      'Would you like to download and install .NET Framework 4.8 now?' + #13#10#13#10 +
      'Click Yes to open download page, No to continue installation anyway.' + #13#10 +
      '(You can install .NET Framework 4.8 later if needed)',
      mbConfirmation,
      MB_YESNO
    ) = IDYES then
    begin
      // Mở trang tải .NET Framework 4.8
      ShellExec('open',
        'https://dotnet.microsoft.com/download/dotnet-framework/net48',
        '',
        '',
        SW_SHOWNORMAL,
        ewNoWait,
        ErrorCode
      );
    end;
    // Cho phép tiếp tục cài đặt dù chưa có .NET Framework
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  // Hiển thị thông báo sau khi cài đặt xong nếu chưa có .NET Framework
  if (CurStep = ssPostInstall) and (not IsDotNet48Installed) then
  begin
    MsgBox(
      'Warning: .NET Framework 4.8 is not installed.' + #13#10#13#10 +
      'Please install .NET Framework 4.8 before running the application.' + #13#10 +
      'Download from: https://dotnet.microsoft.com/download/dotnet-framework/net48',
      mbInformation,
      MB_OK
    );
  end;
end;

